require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Include:
    - "spec/**/*.rb"
    - "lib/**/*.rb"
  Exclude:
    - "tmp/**/*"
    - "log/**/*"
    - "bin/**/*"
    - "vendor/**/*"
    - "test/**/*"

Rails:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Naming/FileName:
  Exclude:
    - "Gemfile"

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%": ()
    "%i": ()
    "%q": ()
    "%Q": ()
    "%r": "{}"
    "%s": ()
    "%w": ()
    "%W": ()
    "%x": ()

Metrics/AbcSize:
  Max: 26

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 50

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Enabled: false

Naming/InclusiveLanguage:
  Exclude:
    - config/environments/production.rb

Rails/SkipsModelValidations:
  AllowedMethods:
    - insert_all
    - upsert_all
    - insert_all!
